### ISSUE TITLE
Will this be shipped in the normal detection process

### ISSUE THREAD

**Issue by josegonzalez** [heroku/heroku-buildpack-dotnet#24]
Hello there. While I noticed this buildpack was recently launched, it seems the instructions do not end at "just include certain files in the repo", and instead require setting the buildpack. Does that mean it won't be officially detected like the buildpacks listed [here](https://devcenter.heroku.com/articles/buildpacks)?

I'm excited about official support for new languages by Heroku, so congrats on the launch!

**Comment by edmorley** [comment]
@josegonzalez Hi! The buildpack only needs to be set explicitly on Heroku during the beta - it will be added to the default language detection list later.

**Comment by josegonzalez** [comment]
Gotcha. I'll keep my eyes open as ya'll move on dotnet support. Exciting to see more adoption of Dotnet on Linux (used it at $job-2 when it wasn't clear what it should look like) in the PaaS ecosystem!
